dist: trusty

sudo: true

language: php

php:
  - '7.1'

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate:install
  - php artisan migrate

addons:
  sonarcloud:
    organization: "tititoof-github"
    token:
      secure: 0e30935ba286454a9a68e24eb560f8b02eb3ad4c

script:
  - vendor/bin/phpunit
  - sonar-scanner

services:
  - sqlite
