dist: trusty
sudo: required
language: php

php:
  - '7.1'

install:
  - bash .travis.install-mysql-5.7.sh
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - travis_retry composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate:install
  - php artisan migrate
  - php artisan dusk:install
  - npm install
  - npm run dev

before_script:
  - phantomjs --webdriver=127.0.0.1:9515 & # Start PhantomJS driver
  - php artisan serve > /dev/null 2>&1 &
  - sleep 5

addons:
  sonarcloud:
    organization: "tititoof-github"
    token:
      secure: 0e30935ba286454a9a68e24eb560f8b02eb3ad4c

script:
  - vendor/bin/phpunit
  - php artisan dusk
  - sonar-scanner

services:
  - mysql

env:
  - TRAVIS_NODE_VERSION="8"
